import sys
import logging
from integrations.email_notify import EmailNotifier

logging.basicConfig(level=logging.INFO)

def main():
    print("Testing Email Notification Feature...")
    
    # Initialize the notifier (it will load the config.yaml automatically)
    notifier = EmailNotifier("integrations/config.yaml")
    
    # Check if enabled
    if not notifier.cfg.get('enabled'):
        print("Email notifications are disabled in config.yaml. Please set enabled: true")
        return

    # Check if credentials are placeholders
    sender = notifier.cfg.get('sender_email')
    password = notifier.cfg.get('sender_password')
    
    if sender == "YOUR_OUTLOOK_EMAIL@outlook.com" or password == "YOUR_APP_PASSWORD_HERE":
        print("Please update 'integrations/config.yaml' with your actual Outlook email and App Password.")
        return

    # Recipients
    recipients = notifier.cfg.get('daily_report_recipients', [])
    if not recipients or recipients[0] == "manager@company.com":
        print("Warning: Please ensure you have added real email addresses to 'daily_report_recipients' in config.yaml")

    subject = "Test Notification from KPI Agent"
    body = "Hello! This is a test message automatically generated by the KPI Agent to verify your Outlook SMTP setup."
    
    print(f"Attempting to send test email from {sender} to {recipients}...")
    success = notifier.send(subject, body, recipients)
    
    if success:
        print("Success! Test email was sent. Please check the recipient inboxes.")
    else:
        print("Failed to send email. Check the logs above for any SMTP authentication errors.")

if __name__ == "__main__":
    main()
